- name: Install python3, docker, Docker-compose, docker python module and start docker
  hosts: aws_ec2 # all
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3, docker, Docker-compose, docker python module and start docker
      vars:
        ansible_python_interpreter: /usr/bin/python 
      yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present      
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-{{lookup('pipe', 'uname -m')}} 
        dest: /usr/local/bin/docker-compose
        mode: +x    
    - name: Start docker daemon
      systemd: 
        name: docker
        state: started
    - name: Install docker python module
      pip: 
        name: 
          - docker
          - docker-compose
    

- name: Create new linux user
  hosts: aws_ec2 # all
  become: yes
  vars:
    user_groups: adm, docker
  roles:
    - create_user





- name: Start docker containers
  hosts: aws_ec2 # all
  become: yes
  become_user: pedro  
  vars_files:
    - project-vars
  roles:
    - start_containers

        


    