- name: Copy docker compose
  copy: 
    src: docker-compose.yaml
    dest: /home/pedro/docker-compose.yaml

- name: Docker login
  docker_login: 
    registry_url: "{{ docker_registry }}"  # For Docker
    username: "{{ docker_username }}"
    password: "{{ docker_password }}" 

- name: Start container from compose 
  docker_compose:
    project_src: /home/pedro